"""baseline_sync_all_models

Revision ID: 83aadcb07de8
Revises: 
Create Date: 2026-07-09 22:45:44.877217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83aadcb07de8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='操作用户 ID（未登录时为 None）'),
    sa.Column('action', sa.String(length=32), nullable=False, comment='操作类型: CREATE / READ / UPDATE / DELETE / LOGIN / EXPORT / DELETE_ACCOUNT'),
    sa.Column('resource', sa.String(length=128), nullable=False, comment='操作资源路径，如 /api/users/me'),
    sa.Column('detail', sa.Text(), nullable=True, comment='操作详情（JSON 格式的摘要信息）'),
    sa.Column('ip', sa.String(length=45), nullable=False, comment='客户端 IP 地址'),
    sa.Column('user_agent', sa.String(length=512), nullable=True, comment='客户端 User-Agent'),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='操作时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('idx_audit_user_action', 'audit_logs', ['user_id', 'timestamp'], unique=False)
    op.create_index('idx_audit_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('crm_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='所属用户 ID'),
    sa.Column('contact_id', sa.Integer(), nullable=True, comment='关联 CRM 联系人 ID'),
    sa.Column('deal_id', sa.Integer(), nullable=True, comment='关联销售机会 ID'),
    sa.Column('doc_type', sa.String(length=16), nullable=False, comment='文档类型: quotation | contract | proposal'),
    sa.Column('template_name', sa.String(length=64), nullable=False, comment='模板名称(预设模板的 key)'),
    sa.Column('title', sa.String(length=256), nullable=False, comment='文档标题'),
    sa.Column('doc_number', sa.String(length=32), nullable=False, comment='文档编号 Q-YYYYMMDD-XXXX / C-... / P-...'),
    sa.Column('content_html', sa.Text(), nullable=False, comment='渲染后的 HTML 内容'),
    sa.Column('content_data', postgresql.JSON(astext_type=Text()), nullable=False, comment='填写的变量数据 {key: value}'),
    sa.Column('total_amount', sa.Float(), nullable=False, comment='总金额'),
    sa.Column('currency', sa.String(length=8), nullable=False, comment='币种'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='draft(草稿) | final(定稿) | sent(已发送) | signed(已签署)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_documents_owner_id'), 'crm_documents', ['owner_id'], unique=False)
    op.create_table('crm_sync_conflicts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_state_id', sa.Integer(), nullable=False, comment='关联 SyncState ID'),
    sa.Column('provider', sa.String(length=32), nullable=False, comment='CRM 提供商'),
    sa.Column('local_contact_id', sa.String(length=64), nullable=False, comment='本地联系人 ID'),
    sa.Column('crm_contact_id', sa.String(length=64), nullable=False, comment='CRM 侧联系人 ID'),
    sa.Column('local_data', sa.Text(), nullable=False, comment='本地数据快照（JSON）'),
    sa.Column('crm_data', sa.Text(), nullable=False, comment='CRM 侧数据快照（JSON）'),
    sa.Column('conflicted_fields', sa.String(length=256), nullable=False, comment='冲突字段列表'),
    sa.Column('detected_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='冲突检测时间'),
    sa.Column('resolved', sa.Boolean(), nullable=False, comment='是否已解决'),
    sa.Column('resolution', sa.String(length=32), nullable=False, comment='解决方法'),
    sa.Column('resolved_at', sa.DateTime(), nullable=True, comment='解决时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_sync_conflicts_provider'), 'crm_sync_conflicts', ['provider'], unique=False)
    op.create_index(op.f('ix_crm_sync_conflicts_sync_state_id'), 'crm_sync_conflicts', ['sync_state_id'], unique=False)
    op.create_table('crm_sync_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False, comment='CRM 提供商标识'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='同步状态'),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='同步开始时间'),
    sa.Column('finished_at', sa.DateTime(), nullable=True, comment='同步完成时间'),
    sa.Column('contacts_created', sa.Integer(), nullable=False, comment='新建联系人数量'),
    sa.Column('contacts_updated', sa.Integer(), nullable=False, comment='更新联系人数量'),
    sa.Column('contacts_deleted', sa.Integer(), nullable=False, comment='删除联系人数量'),
    sa.Column('contacts_conflicted', sa.Integer(), nullable=False, comment='冲突联系人数量'),
    sa.Column('error_message', sa.Text(), nullable=False, comment='错误信息摘要'),
    sa.Column('details', sa.Text(), nullable=False, comment='同步详情（JSON）'),
    sa.Column('trigger', sa.String(length=16), nullable=False, comment='触发方式'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_sync_states_provider'), 'crm_sync_states', ['provider'], unique=False)
    op.create_table('developer_apps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户 ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='应用名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='应用描述'),
    sa.Column('website', sa.String(length=512), nullable=True, comment='应用网站 URL'),
    sa.Column('redirect_uris', sa.Text(), nullable=True, comment='OAuth2 回调 URI (逗号分隔)'),
    sa.Column('client_id', sa.String(length=64), nullable=False, comment='客户端 ID (app_xxx)'),
    sa.Column('client_secret_hash', sa.String(length=128), nullable=False, comment='client_secret 的 SHA256 哈希'),
    sa.Column('client_secret_prefix', sa.String(length=8), nullable=False, comment='secret 前 8 位用于显示'),
    sa.Column('scopes', sa.String(length=500), nullable=False, comment='权限范围 JSON 数组字符串'),
    sa.Column('active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_developer_apps_client_id'), 'developer_apps', ['client_id'], unique=True)
    op.create_index(op.f('ix_developer_apps_id'), 'developer_apps', ['id'], unique=False)
    op.create_index(op.f('ix_developer_apps_user_id'), 'developer_apps', ['user_id'], unique=False)
    op.create_table('email_campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False, comment='活动名称'),
    sa.Column('subject', sa.String(length=512), nullable=False, comment='邮件主题'),
    sa.Column('content_template', sa.Text(), nullable=False, comment='邮件内容模板（HTML/纯文本）'),
    sa.Column('target_segment', sa.Text(), nullable=False, comment='目标人群段(JSON): {tags:[], pipeline_stage_ids:[], sources:[], created_after:, created_before:}'),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True, comment='计划发送时间'),
    sa.Column('sent_count', sa.Integer(), nullable=False, comment='已发送数'),
    sa.Column('open_count', sa.Integer(), nullable=False, comment='已打开数'),
    sa.Column('click_count', sa.Integer(), nullable=False, comment='点击数'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='draft | scheduled | sending | sent | paused | cancelled'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enterprise_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='管理员用户ID'),
    sa.Column('company_name', sa.String(length=128), nullable=False, comment='企业名称'),
    sa.Column('seats', sa.Integer(), nullable=False, comment='席位数量'),
    sa.Column('tier', sa.String(length=32), nullable=False, comment='套餐等级: free/standard/enterprise'),
    sa.Column('start_date', sa.DateTime(), nullable=False, comment='订阅开始时间'),
    sa.Column('end_date', sa.DateTime(), nullable=False, comment='订阅到期时间'),
    sa.Column('auto_renew', sa.Boolean(), nullable=False, comment='是否自动续费'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态: active/trial/expired/cancelled'),
    sa.Column('features', postgresql.JSON(astext_type=Text()), nullable=False, comment='功能特性配置(JSON)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gaia_evolution_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False, comment='事件类型: knowledge_ingested | feedback_recorded | cycle_started | cycle_completed | weights_updated | training_started | training_completed | training_failed'),
    sa.Column('event_source', sa.String(length=32), nullable=False, comment='事件来源: api | scheduler | manual | internal'),
    sa.Column('description', sa.String(length=512), nullable=False, comment='事件描述'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='事件元数据（JSON，存储上下文信息）'),
    sa.Column('reference_type', sa.String(length=32), nullable=True, comment='关联对象类型: knowledge | feedback | training_run | weights'),
    sa.Column('reference_id', sa.Integer(), nullable=True, comment='关联对象ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='事件发生时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gaia_event_ref', 'gaia_evolution_events', ['reference_type', 'reference_id'], unique=False)
    op.create_index('idx_gaia_event_type_time', 'gaia_evolution_events', ['event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_gaia_evolution_events_created_at'), 'gaia_evolution_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_gaia_evolution_events_event_type'), 'gaia_evolution_events', ['event_type'], unique=False)
    op.create_table('gaia_knowledge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False, comment='知识来源: retrospective | feedback | ab_test | manual | system'),
    sa.Column('source_id', sa.String(length=64), nullable=True, comment='来源标识（如复盘ID、反馈ID、实验ID）'),
    sa.Column('knowledge_type', sa.String(length=32), nullable=False, comment='知识类型: insight | pattern | rule | preference | behavior | optimization'),
    sa.Column('title', sa.String(length=256), nullable=False, comment='知识标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='知识详细内容'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签（JSON数组: ["标签1", "标签2"]）'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='置信度 0.0 ~ 1.0'),
    sa.Column('impact_score', sa.Float(), nullable=False, comment='影响评分，用于知识权重排序'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活（软删除标记）'),
    sa.Column('vector_embedded', sa.Boolean(), nullable=False, comment='是否已向量化'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gaia_knowledge_active', 'gaia_knowledge', ['is_active', 'created_at'], unique=False)
    op.create_index('idx_gaia_knowledge_source', 'gaia_knowledge', ['source', 'source_id'], unique=False)
    op.create_index('idx_gaia_knowledge_type', 'gaia_knowledge', ['knowledge_type', 'confidence'], unique=False)
    op.create_index(op.f('ix_gaia_knowledge_knowledge_type'), 'gaia_knowledge', ['knowledge_type'], unique=False)
    op.create_index(op.f('ix_gaia_knowledge_source'), 'gaia_knowledge', ['source'], unique=False)
    op.create_table('gaia_model_weights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module', sa.String(length=64), nullable=False, comment='模块标识: recommendation | search | extractor | writing | optimization | rag | knowledge_graph'),
    sa.Column('weights', sa.JSON(), nullable=False, comment='权重字典（JSON, 结构因模块而异）'),
    sa.Column('version', sa.String(length=32), nullable=False, comment='权重版本号'),
    sa.Column('description', sa.String(length=512), nullable=False, comment='版本变更说明'),
    sa.Column('training_run_id', sa.Integer(), nullable=True, comment='关联的训练记录ID'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否为当前活跃版本'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gaia_weights_module_active', 'gaia_model_weights', ['module', 'is_active', 'version'], unique=False)
    op.create_index(op.f('ix_gaia_model_weights_module'), 'gaia_model_weights', ['module'], unique=False)
    op.create_table('gaia_training_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态: pending | running | completed | failed'),
    sa.Column('trigger', sa.String(length=32), nullable=False, comment='触发方式: manual | scheduled | automatic | api'),
    sa.Column('knowledge_count', sa.Integer(), nullable=False, comment='本次训练使用的知识条目数'),
    sa.Column('feedback_count', sa.Integer(), nullable=False, comment='本次训练使用的反馈条目数'),
    sa.Column('weights_count', sa.Integer(), nullable=False, comment='本次训练更新的权重数'),
    sa.Column('vector_index_size', sa.Integer(), nullable=False, comment='向量索引条目数'),
    sa.Column('duration_ms', sa.Integer(), nullable=False, comment='训练耗时（毫秒）'),
    sa.Column('metrics', sa.JSON(), nullable=True, comment='训练指标（JSON: {"accuracy": 0.95, "coverage": 0.8, ...}）'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息（失败时记录）'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='训练开始时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='训练完成时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gaia_training_status', 'gaia_training_runs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_gaia_training_runs_status'), 'gaia_training_runs', ['status'], unique=False)
    op.create_table('integrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户ID'),
    sa.Column('provider', sa.String(length=32), nullable=False, comment='集成类型: hubspot / salesforce / webhook'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='集成名称（用户自定义）'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('config', sa.Text(), nullable=False, comment='JSON 配置（API Key、Token、端点等）'),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True, comment='最后成功同步时间'),
    sa.Column('webhook_url', sa.String(length=512), nullable=False, comment='Webhook 回调 URL'),
    sa.Column('webhook_secret', sa.String(length=128), nullable=False, comment='Webhook 签名密钥'),
    sa.Column('webhook_enabled', sa.Boolean(), nullable=False, comment='是否启用 Webhook'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrations_user_id'), 'integrations', ['user_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_no', sa.String(length=32), nullable=False, comment='发票号 INV-YYYYMMDD-XXXX'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('amount', sa.Float(), nullable=False, comment='不含税金额'),
    sa.Column('tax_rate', sa.Float(), nullable=False, comment='税率（%），如 3、6、13'),
    sa.Column('tax_amount', sa.Float(), nullable=False, comment='税额'),
    sa.Column('total_amount', sa.Float(), nullable=False, comment='含税总金额'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态: paid/unpaid/cancelled'),
    sa.Column('order_no', sa.String(length=32), nullable=False, comment='关联支付订单号'),
    sa.Column('buyer_name', sa.String(length=128), nullable=False, comment='购买方名称'),
    sa.Column('buyer_tax_id', sa.String(length=32), nullable=False, comment='购买方税号'),
    sa.Column('seller_name', sa.String(length=128), nullable=False, comment='销售方名称'),
    sa.Column('seller_tax_id', sa.String(length=32), nullable=False, comment='销售方税号'),
    sa.Column('items', postgresql.JSON(astext_type=Text()), nullable=False, comment='发票项 [{description, quantity, unit_price, amount}]'),
    sa.Column('notes', sa.Text(), nullable=False, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_no')
    )
    op.create_table('knowledge_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.String(length=32), nullable=False, comment='模型编码，如 FD-M01 (Frontend Design Mental Model 01)'),
    sa.Column('category', sa.String(length=32), nullable=False, comment='分类: design_system | ui_principle | ux_interaction | visual_design | process_methodology | domain_specific'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='模型名称'),
    sa.Column('source', sa.String(length=64), nullable=False, comment='来源: manual | ai_distilled | design_system | training | feedback'),
    sa.Column('source_ref', sa.String(length=256), nullable=True, comment='来源引用（文件路径、URL、论文引用等）'),
    sa.Column('content', sa.Text(), nullable=False, comment='模型内容 — 详细描述、定义和应用场景'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签（JSON数组）'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='置信度 0.0 ~ 1.0'),
    sa.Column('version', sa.String(length=16), nullable=False, comment='模型版本号'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('vector_embedded', sa.Boolean(), nullable=False, comment='是否已向量化'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_km_active', 'knowledge_models', ['is_active', 'created_at'], unique=False)
    op.create_index('idx_km_category', 'knowledge_models', ['category', 'confidence'], unique=False)
    op.create_index('idx_km_model_id', 'knowledge_models', ['model_id'], unique=False)
    op.create_index(op.f('ix_knowledge_models_category'), 'knowledge_models', ['category'], unique=False)
    op.create_index(op.f('ix_knowledge_models_model_id'), 'knowledge_models', ['model_id'], unique=True)
    op.create_table('payment_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=False, comment='内部订单号'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('membership_tier', sa.String(length=16), nullable=False, comment='会员等级'),
    sa.Column('channel', sa.String(length=16), nullable=False, comment='支付渠道: wechat/alipay'),
    sa.Column('channel_order_no', sa.String(length=64), nullable=False, comment='渠道订单号'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='支付状态'),
    sa.Column('total_cents', sa.Integer(), nullable=False, comment='金额（分）'),
    sa.Column('paid_at', sa.DateTime(), nullable=True, comment='支付时间'),
    sa.Column('raw_callback', sa.String(length=2048), nullable=False, comment='原始回调数据'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_table('rbac_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False, comment='角色标识'),
    sa.Column('display_name', sa.String(length=64), nullable=False, comment='角色显示名'),
    sa.Column('description', sa.Text(), nullable=False, comment='角色描述'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='系统预置角色（不可删除）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('social_connections',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='发起方用户ID'),
    sa.Column('contact_id', sa.Integer(), nullable=False, comment='目标方用户ID'),
    sa.Column('source', sa.String(length=32), nullable=False, comment='来源: qrcode / manual / share'),
    sa.Column('message', sa.Text(), nullable=False, comment='建联附言'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态: pending / approved / rejected'),
    sa.Column('strength', sa.Float(), nullable=False, comment='关系强度 (0.0 ~ 1.0)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='租户名称'),
    sa.Column('slug', sa.String(length=64), nullable=False, comment='唯一标识'),
    sa.Column('plan', sa.String(length=16), nullable=False, comment='套餐: FREE/PRO/ENTERPRISE'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('trial_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('subscription_id', sa.Integer(), nullable=False, comment='关联的订阅ID'),
    sa.Column('trial_tier', sa.String(length=32), nullable=False, comment='试用套餐等级'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态: active/used/expired'),
    sa.Column('started_at', sa.DateTime(), nullable=False, comment='试用开始时间'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='试用到期时间'),
    sa.Column('converted_at', sa.DateTime(), nullable=True, comment='转为正式订阅的时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unlock_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='解锁方用户ID'),
    sa.Column('target_user_id', sa.Integer(), nullable=False, comment='被解锁的用户ID'),
    sa.Column('match_record_id', sa.Integer(), nullable=False, comment='关联的匹配记录ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_counters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('feature', sa.String(length=32), nullable=False, comment='功能标识: ocr/visitor/batch_import/api/card'),
    sa.Column('period', sa.String(length=16), nullable=False, comment='统计周期: monthly'),
    sa.Column('used_count', sa.Integer(), nullable=False, comment='已使用次数'),
    sa.Column('limit_count', sa.Integer(), nullable=False, comment='周期上限（-1=无限制）'),
    sa.Column('reset_at', sa.DateTime(), nullable=True, comment='限额重置时间'),
    sa.Column('model_type', sa.String(length=16), nullable=False, comment='模型类型: internal/external'),
    sa.Column('model_name', sa.String(length=64), nullable=False, comment='模型名称: deepseek-chat/m3e 等'),
    sa.Column('token_type', sa.String(length=16), nullable=False, comment='Token 类型: chat/embedding/search/rule/query'),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False, comment='输入 token 数（外部模型）'),
    sa.Column('completion_tokens', sa.Integer(), nullable=False, comment='输出 token 数（外部模型）'),
    sa.Column('total_tokens', sa.Integer(), nullable=False, comment='总 token 数'),
    sa.Column('token_cost', sa.Float(), nullable=False, comment='用户费用（¥）'),
    sa.Column('external_cost', sa.Float(), nullable=False, comment='外部模型成本（¥，仅 external 有效）'),
    sa.Column('markup_rate', sa.Float(), nullable=False, comment='加价率（external 默认 0.5）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'feature', 'period', name='uq_usage_user_feature_period')
    )
    op.create_index(op.f('ix_usage_counters_user_id'), 'usage_counters', ['user_id'], unique=False)
    op.create_table('webhook_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='订阅名称（用户自定义）'),
    sa.Column('url', sa.String(length=512), nullable=False, comment='Webhook 回调 URL'),
    sa.Column('secret', sa.String(length=128), nullable=False, comment='签名密钥（用于 HMAC-SHA256 签名）'),
    sa.Column('events', sa.Text(), nullable=False, comment='监听的事件类型列表，JSON 数组'),
    sa.Column('active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='失败重试次数'),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False, comment='HTTP 请求超时秒数'),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True, comment='上次触发时间'),
    sa.Column('last_response_code', sa.Integer(), nullable=True, comment='上次响应状态码'),
    sa.Column('last_error', sa.Text(), nullable=False, comment='上次错误信息'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_subscriptions_user_id'), 'webhook_subscriptions', ['user_id'], unique=False)
    op.create_table('rbac_role_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_key', sa.String(length=64), nullable=False, comment='权限标识'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['rbac_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_key', name='uq_role_permission')
    )
    op.create_table('rbac_user_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户 ID'),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('granted_by', sa.Integer(), nullable=True, comment='授权人用户 ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['rbac_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('wechat_openid', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('company', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('intro', sa.Text(), nullable=False),
    sa.Column('avatar', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False, comment='可见性: public/platform/network/private'),
    sa.Column('membership_tier', sa.String(length=16), nullable=False, comment='会员等级: free/gold/diamond/board'),
    sa.Column('membership_expires_at', sa.DateTime(), nullable=True, comment='会员过期时间'),
    sa.Column('membership_synced_at', sa.DateTime(), nullable=True, comment='最后同步链客宝时间'),
    sa.Column('unlock_quota', sa.Integer(), nullable=False, comment='本月剩余解锁配额'),
    sa.Column('quota_reset_at', sa.DateTime(), nullable=True, comment='配额重置时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='所属租户 ID'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('wechat_openid')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False, comment='API Key 值（完整）'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='Key 名称（用户自定义标识）'),
    sa.Column('permissions', sa.Text(), nullable=False, comment='权限列表 JSON 数组，例如 ["read", "write", "admin"]'),
    sa.Column('rate_limit', sa.Integer(), nullable=False, comment='每小时速率限制（请求数/小时）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('last_used_at', sa.DateTime(), nullable=True, comment='最后使用时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('app_store_plugins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=False, comment='开发者用户 ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='插件名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='插件描述'),
    sa.Column('icon_url', sa.String(length=512), nullable=True, comment='图标 URL'),
    sa.Column('category', sa.String(length=64), nullable=False, comment='分类: tools/analytics/automation/communication/ai/custom'),
    sa.Column('version', sa.String(length=32), nullable=False, comment='当前版本号'),
    sa.Column('price', sa.Float(), nullable=False, comment='价格 (0=免费)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: draft/pending/review/published/rejected'),
    sa.Column('install_count', sa.Integer(), nullable=False, comment='安装次数'),
    sa.Column('rating', sa.Float(), nullable=False, comment='评分 (0-5)'),
    sa.Column('rating_count', sa.Integer(), nullable=False, comment='评分人数'),
    sa.Column('homepage_url', sa.String(length=512), nullable=True, comment='项目主页'),
    sa.Column('documentation_url', sa.String(length=512), nullable=True, comment='文档地址'),
    sa.Column('repository_url', sa.String(length=512), nullable=True, comment='源码仓库'),
    sa.Column('tags', sa.String(length=512), nullable=True, comment='标签 (逗号分隔)'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['developer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_store_plugins_category'), 'app_store_plugins', ['category'], unique=False)
    op.create_index(op.f('ix_app_store_plugins_developer_id'), 'app_store_plugins', ['developer_id'], unique=False)
    op.create_index(op.f('ix_app_store_plugins_id'), 'app_store_plugins', ['id'], unique=False)
    op.create_index(op.f('ix_app_store_plugins_status'), 'app_store_plugins', ['status'], unique=False)
    op.create_table('brochures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('cover', sa.String(length=256), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('pages_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('share_token', sa.String(length=32), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('album_meta', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='所属租户 ID'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_index(op.f('ix_brochures_tenant_id'), 'brochures', ['tenant_id'], unique=False)
    op.create_table('crm_campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False, comment='活动名称'),
    sa.Column('subject', sa.String(length=512), nullable=False, comment='邮件主题'),
    sa.Column('template_name', sa.String(length=64), nullable=False, comment='模板名称(对应 email_templates 中的函数名)'),
    sa.Column('template_params', sa.Text(), nullable=False, comment='模板参数(JSON)'),
    sa.Column('target_filter', sa.Text(), nullable=False, comment='目标筛选条件(JSON): {tags:[], pipeline_stage_ids:[], sources:[], created_after:, created_before:}'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='draft | sending | sent | paused'),
    sa.Column('total_recipients', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('opened_count', sa.Integer(), nullable=False),
    sa.Column('unsubscribed_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_campaigns_owner_id'), 'crm_campaigns', ['owner_id'], unique=False)
    op.create_table('crm_pipeline_stages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='阶段名称'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('color', sa.String(length=16), nullable=False, comment='显示颜色'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否是新联系人默认阶段'),
    sa.Column('is_closed', sa.Boolean(), nullable=False, comment='是否终止阶段(成交/丢失)'),
    sa.Column('win_probability', sa.Float(), nullable=False, comment='该阶段的默认赢单率(0-100)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_pipeline_stages_user_id'), 'crm_pipeline_stages', ['user_id'], unique=False)
    op.create_table('crm_workflow_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='规则名称'),
    sa.Column('description', sa.Text(), nullable=False, comment='规则描述'),
    sa.Column('trigger_event', sa.String(length=32), nullable=False, comment='触发事件: contact_added | deal_created | stage_changed'),
    sa.Column('conditions', sa.Text(), nullable=False, comment='条件列表(JSON): [{"field":"source","operator":"eq","value":"manual"}]'),
    sa.Column('actions', sa.Text(), nullable=False, comment='动作列表(JSON): [{"type":"send_email","config":{...}}]'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_workflow_rules_owner_id'), 'crm_workflow_rules', ['owner_id'], unique=False)
    op.create_table('developer_reward_balances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=False, comment='开发者 ID'),
    sa.Column('total_points', sa.Integer(), nullable=False, comment='总获得积分'),
    sa.Column('used_points', sa.Integer(), nullable=False, comment='已使用积分'),
    sa.Column('balance', sa.Integer(), nullable=False, comment='可用余额'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['developer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_developer_reward_balances_developer_id'), 'developer_reward_balances', ['developer_id'], unique=True)
    op.create_index(op.f('ix_developer_reward_balances_id'), 'developer_reward_balances', ['id'], unique=False)
    op.create_table('developer_rewards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=False, comment='开发者 ID'),
    sa.Column('reward_type', sa.String(length=32), nullable=False, comment='奖励类型: install/quality/activity/bonus'),
    sa.Column('points', sa.Integer(), nullable=False, comment='奖励积分'),
    sa.Column('reason', sa.String(length=256), nullable=True, comment='奖励原因'),
    sa.Column('source_id', sa.Integer(), nullable=True, comment='来源 ID (如插件ID)'),
    sa.Column('source_desc', sa.String(length=128), nullable=True, comment='来源描述'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: pending/issued/cancelled'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('issued_at', sa.DateTime(), nullable=True, comment='发放时间'),
    sa.ForeignKeyConstraint(['developer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_developer_rewards_developer_id'), 'developer_rewards', ['developer_id'], unique=False)
    op.create_index(op.f('ix_developer_rewards_id'), 'developer_rewards', ['id'], unique=False)
    op.create_table('match_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_a_id', sa.Integer(), nullable=False),
    sa.Column('user_b_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('common_tags', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_is_read'), 'messages', ['is_read'], unique=False)
    op.create_index(op.f('ix_messages_receiver_id'), 'messages', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_table('resource_platforms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('platform_no', sa.String(length=50), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('annual_fee', sa.Integer(), nullable=False, comment='年费(分)'),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('member_limit', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False, comment='可见性: public/platform/network/private'),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_no')
    )
    op.create_table('reward_redemptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=False, comment='开发者 ID'),
    sa.Column('points_spent', sa.Integer(), nullable=False, comment='花费积分'),
    sa.Column('redemption_type', sa.String(length=32), nullable=False, comment='兑换类型: api_quota/promotion'),
    sa.Column('quota_amount', sa.Integer(), nullable=True, comment='兑换数量 (如 API 调用次数)'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='兑换描述'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: completed/cancelled'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='兑换时间'),
    sa.ForeignKeyConstraint(['developer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_redemptions_developer_id'), 'reward_redemptions', ['developer_id'], unique=False)
    op.create_index(op.f('ix_reward_redemptions_id'), 'reward_redemptions', ['id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='团队名称'),
    sa.Column('slug', sa.String(length=64), nullable=False, comment='唯一标识 slug'),
    sa.Column('description', sa.Text(), nullable=False, comment='团队简介'),
    sa.Column('logo', sa.String(length=256), nullable=False, comment='团队 Logo URL'),
    sa.Column('website', sa.String(length=256), nullable=False, comment='团队网站'),
    sa.Column('industry', sa.String(length=64), nullable=False, comment='所属行业'),
    sa.Column('size', sa.String(length=16), nullable=False, comment='团队规模'),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='创建者/所有者'),
    sa.Column('max_members', sa.Integer(), nullable=False, comment='最大成员数'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('visibility', sa.String(length=20), nullable=False, comment='可见性: public/platform/network/private'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('trust_network',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trusted_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trusted_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tag_type', sa.String(length=16), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ab_tests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('traffic_fraction', sa.Float(), nullable=False),
    sa.Column('min_sample_size', sa.Integer(), nullable=False),
    sa.Column('significance_level', sa.Float(), nullable=False),
    sa.Column('metric', sa.String(length=32), nullable=False),
    sa.Column('target_brochure_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cached_results', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['target_brochure_id'], ['brochures.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ab_tests_status'), 'ab_tests', ['status'], unique=False)
    op.create_index(op.f('ix_ab_tests_target_brochure_id'), 'ab_tests', ['target_brochure_id'], unique=False)
    op.create_index(op.f('ix_ab_tests_user_id'), 'ab_tests', ['user_id'], unique=False)
    op.create_table('api_key_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False, comment='统计日期 YYYY-MM-DD'),
    sa.Column('request_count', sa.Integer(), nullable=False, comment='当日请求数'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_key_usage_api_key_id'), 'api_key_usage', ['api_key_id'], unique=False)
    op.create_table('app_store_plugin_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False, comment='审核员 ID'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='审核结果: approved/rejected'),
    sa.Column('comments', sa.Text(), nullable=True, comment='审核意见'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='审核时间'),
    sa.ForeignKeyConstraint(['plugin_id'], ['app_store_plugins.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_store_plugin_reviews_id'), 'app_store_plugin_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_app_store_plugin_reviews_plugin_id'), 'app_store_plugin_reviews', ['plugin_id'], unique=False)
    op.create_table('app_store_plugin_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False, comment='版本号 (semver)'),
    sa.Column('changelog', sa.Text(), nullable=True, comment='更新日志'),
    sa.Column('download_url', sa.String(length=512), nullable=True, comment='下载地址'),
    sa.Column('required_api_version', sa.String(length=32), nullable=False, comment='最低 API 版本'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小 (字节)'),
    sa.Column('checksum', sa.String(length=128), nullable=True, comment='文件校验和 (SHA256)'),
    sa.Column('is_published', sa.Integer(), nullable=False, comment='是否发布 (0/1)'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['plugin_id'], ['app_store_plugins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_store_plugin_versions_id'), 'app_store_plugin_versions', ['id'], unique=False)
    op.create_index(op.f('ix_app_store_plugin_versions_plugin_id'), 'app_store_plugin_versions', ['plugin_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False, comment='团队ID'),
    sa.Column('requester_id', sa.Integer(), nullable=False, comment='请求人ID'),
    sa.Column('action', sa.Enum('JOIN', 'INVITE', 'UPGRADE', 'REMOVE', name='approvalaction'), nullable=False, comment='动作类型'),
    sa.Column('target_user_id', sa.Integer(), nullable=True, comment='目标用户ID'),
    sa.Column('reason', sa.Text(), nullable=True, comment='申请原因'),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus'), nullable=False, comment='状态'),
    sa.Column('reviewer_id', sa.Integer(), nullable=True, comment='审批人ID'),
    sa.Column('reject_reason', sa.Text(), nullable=True, comment='拒绝原因'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True, comment='审批时间'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='CRM所属用户'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='关联的平台用户(名片交换对方)'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='姓名'),
    sa.Column('phone', sa.String(length=32), nullable=False, comment='手机号'),
    sa.Column('email', sa.String(length=128), nullable=False, comment='邮箱'),
    sa.Column('company', sa.String(length=256), nullable=False, comment='公司'),
    sa.Column('title', sa.String(length=128), nullable=False, comment='职位'),
    sa.Column('department', sa.String(length=128), nullable=False, comment='部门'),
    sa.Column('avatar', sa.String(length=512), nullable=False, comment='头像URL'),
    sa.Column('intro', sa.Text(), nullable=False, comment='个人简介/备注'),
    sa.Column('source', sa.String(length=16), nullable=False, comment='来源: match(名片交换) | manual(手动) | visitor(访客) | import(导入)'),
    sa.Column('source_record_id', sa.Integer(), nullable=True, comment='来源记录ID(如MatchRecord.id)'),
    sa.Column('visibility', sa.String(length=20), nullable=False, comment='可见性: public/platform/network/private'),
    sa.Column('tags', sa.Text(), nullable=False, comment='联系人标签(JSON数组)'),
    sa.Column('pipeline_stage_id', sa.Integer(), nullable=True, comment='当前管道阶段'),
    sa.Column('deal_value', sa.Numeric(precision=12, scale=2), nullable=True, comment='预估成交金额'),
    sa.Column('deal_currency', sa.String(length=8), nullable=False, comment='币种'),
    sa.Column('last_contacted_at', sa.DateTime(), nullable=True, comment='最后联系时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pipeline_stage_id'], ['crm_pipeline_stages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_contacts_owner_id'), 'crm_contacts', ['owner_id'], unique=False)
    op.create_index(op.f('ix_crm_contacts_user_id'), 'crm_contacts', ['user_id'], unique=False)
    op.create_table('crm_workflow_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=128), nullable=False, comment='规则名称(冗余方便查询)'),
    sa.Column('trigger_event', sa.String(length=32), nullable=False, comment='触发事件'),
    sa.Column('context_snapshot', sa.Text(), nullable=False, comment='触发时的上下文快照(JSON)'),
    sa.Column('action_results', sa.Text(), nullable=False, comment='动作执行结果(JSON)'),
    sa.Column('success', sa.Boolean(), nullable=False, comment='是否全部成功'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['crm_workflow_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_workflow_logs_owner_id'), 'crm_workflow_logs', ['owner_id'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brochure_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=256), nullable=False),
    sa.Column('media_url', sa.String(length=512), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='所属租户 ID'),
    sa.ForeignKeyConstraint(['brochure_id'], ['brochures.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_tenant_id'), 'pages', ['tenant_id'], unique=False)
    op.create_table('platform_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False, comment='secretary_general / secretariat / member'),
    sa.Column('joined_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['resource_platforms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_id', 'user_id', name='uq_platform_user')
    )
    op.create_table('platform_opportunities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('industry', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('budget', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['resource_platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_invites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False, comment='团队ID'),
    sa.Column('inviter_id', sa.Integer(), nullable=False, comment='邀请人ID'),
    sa.Column('invitee_email', sa.String(length=256), nullable=False, comment='被邀请人邮箱'),
    sa.Column('invitee_phone', sa.String(length=20), nullable=False, comment='被邀请人手机号'),
    sa.Column('invitee_id', sa.Integer(), nullable=True, comment='已注册用户的ID'),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='teamrole'), nullable=False, comment='邀请角色'),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED', name='invitestatus'), nullable=False, comment='状态'),
    sa.Column('token', sa.String(length=128), nullable=False, comment='邀请令牌'),
    sa.Column('message', sa.Text(), nullable=False, comment='邀请附言'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='过期时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False, comment='团队ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='teamrole'), nullable=False, comment='角色'),
    sa.Column('title_in_team', sa.String(length=128), nullable=False, comment='在团队中的职位'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否在职'),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='加入时间'),
    sa.Column('invited_by', sa.Integer(), nullable=True, comment='邀请人'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visitor_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brochure_id', sa.Integer(), nullable=False),
    sa.Column('visitor_id', sa.String(length=64), nullable=True),
    sa.Column('visitor_ip', sa.String(length=48), nullable=False),
    sa.Column('visitor_name', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('page_viewed', sa.String(length=64), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('interested', sa.Boolean(), nullable=False),
    sa.Column('contact_msg', sa.Text(), nullable=False),
    sa.Column('visit_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brochure_id'], ['brochures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ab_test_decision_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('variant_name', sa.String(length=64), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['ab_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ab_test_decision_logs_created_at'), 'ab_test_decision_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_ab_test_decision_logs_experiment_id'), 'ab_test_decision_logs', ['experiment_id'], unique=False)
    op.create_table('ab_test_variants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_control', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['ab_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ab_test_variants_experiment_id'), 'ab_test_variants', ['experiment_id'], unique=False)
    op.create_table('app_store_plugin_installs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='安装者'),
    sa.Column('version_id', sa.Integer(), nullable=True, comment='安装版本'),
    sa.Column('is_active', sa.Integer(), nullable=False, comment='是否已安装'),
    sa.Column('installed_at', sa.DateTime(), nullable=True, comment='安装时间'),
    sa.Column('uninstalled_at', sa.DateTime(), nullable=True, comment='卸载时间'),
    sa.ForeignKeyConstraint(['plugin_id'], ['app_store_plugins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['app_store_plugin_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_store_plugin_installs_id'), 'app_store_plugin_installs', ['id'], unique=False)
    op.create_index(op.f('ix_app_store_plugin_installs_plugin_id'), 'app_store_plugin_installs', ['plugin_id'], unique=False)
    op.create_index(op.f('ix_app_store_plugin_installs_user_id'), 'app_store_plugin_installs', ['user_id'], unique=False)
    op.create_table('crm_campaign_recipients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False, comment='收件人邮箱'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='收件人姓名'),
    sa.Column('tracking_token', sa.String(length=64), nullable=False, comment='唯一追踪令牌'),
    sa.Column('sent', sa.Boolean(), nullable=False, comment='是否已发送'),
    sa.Column('sent_at', sa.DateTime(), nullable=True, comment='发送时间'),
    sa.Column('send_error', sa.Text(), nullable=False, comment='发送错误信息'),
    sa.Column('opened', sa.Boolean(), nullable=False, comment='是否已打开'),
    sa.Column('opened_at', sa.DateTime(), nullable=True, comment='打开时间'),
    sa.Column('unsubscribed', sa.Boolean(), nullable=False, comment='是否退订'),
    sa.Column('unsubscribed_at', sa.DateTime(), nullable=True, comment='退订时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['crm_campaigns.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_campaign_recipients_campaign_id'), 'crm_campaign_recipients', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_crm_campaign_recipients_tracking_token'), 'crm_campaign_recipients', ['tracking_token'], unique=True)
    op.create_table('crm_deals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_stage_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False, comment='机会标题'),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False, comment='预估金额'),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False, comment='赢单概率 0-100'),
    sa.Column('expected_close_date', sa.DateTime(), nullable=True, comment='预计成交日期'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='open(进行中) | won(已成交) | lost(已丢失) | paused(暂缓)'),
    sa.Column('lost_reason', sa.Text(), nullable=False, comment='丢单原因'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pipeline_stage_id'], ['crm_pipeline_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_deals_contact_id'), 'crm_deals', ['contact_id'], unique=False)
    op.create_index(op.f('ix_crm_deals_owner_id'), 'crm_deals', ['owner_id'], unique=False)
    op.create_table('customer_journey_stages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=True, comment='关联的管道阶段(可选)'),
    sa.Column('stage', sa.String(length=20), nullable=False, comment='awareness | consideration | decision | retention'),
    sa.Column('entered_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='进入该阶段的时间'),
    sa.Column('duration_days', sa.Integer(), nullable=False, comment='在该阶段停留的天数'),
    sa.Column('actions_taken', sa.Text(), nullable=False, comment="已执行动作(JSON数组): [{'action':'email_sent','date':'...'}, ...]"),
    sa.Column('score', sa.Float(), nullable=False, comment='客户评分(0-100)'),
    sa.Column('next_action', sa.String(length=256), nullable=False, comment='推荐的下一个最佳行动'),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ),
    sa.ForeignKeyConstraint(['pipeline_id'], ['crm_pipeline_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_journey_stages_contact_id'), 'customer_journey_stages', ['contact_id'], unique=False)
    op.create_table('ab_test_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('visitor_id', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['ab_tests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['ab_test_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ab_test_events_created_at'), 'ab_test_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_ab_test_events_experiment_id'), 'ab_test_events', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_ab_test_events_user_id'), 'ab_test_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_ab_test_events_variant_id'), 'ab_test_events', ['variant_id'], unique=False)
    op.create_index(op.f('ix_ab_test_events_visitor_id'), 'ab_test_events', ['visitor_id'], unique=False)
    op.create_table('crm_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True, comment='关联的机会'),
    sa.Column('activity_type', sa.String(length=16), nullable=False, comment='类型: call | meeting | email | note | message | match | visit | system'),
    sa.Column('title', sa.String(length=256), nullable=False, comment='活动标题'),
    sa.Column('description', sa.Text(), nullable=False, comment='活动描述/纪要'),
    sa.Column('source_model', sa.String(length=32), nullable=True, comment='来源表名(如messages/visitor_logs)'),
    sa.Column('source_record_id', sa.Integer(), nullable=True, comment='来源记录ID'),
    sa.Column('activity_date', sa.DateTime(), nullable=False, comment='活动发生时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['crm_deals.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_activities_contact_id'), 'crm_activities', ['contact_id'], unique=False)
    op.create_index(op.f('ix_crm_activities_owner_id'), 'crm_activities', ['owner_id'], unique=False)
    op.create_table('crm_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True, comment='关联联系人'),
    sa.Column('deal_id', sa.Integer(), nullable=True, comment='关联机会'),
    sa.Column('content', sa.Text(), nullable=False, comment='笔记内容'),
    sa.Column('is_pinned', sa.Boolean(), nullable=False, comment='是否置顶'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['crm_deals.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_notes_owner_id'), 'crm_notes', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crm_notes_owner_id'), table_name='crm_notes')
    op.drop_table('crm_notes')
    op.drop_index(op.f('ix_crm_activities_owner_id'), table_name='crm_activities')
    op.drop_index(op.f('ix_crm_activities_contact_id'), table_name='crm_activities')
    op.drop_table('crm_activities')
    op.drop_index(op.f('ix_ab_test_events_visitor_id'), table_name='ab_test_events')
    op.drop_index(op.f('ix_ab_test_events_variant_id'), table_name='ab_test_events')
    op.drop_index(op.f('ix_ab_test_events_user_id'), table_name='ab_test_events')
    op.drop_index(op.f('ix_ab_test_events_experiment_id'), table_name='ab_test_events')
    op.drop_index(op.f('ix_ab_test_events_created_at'), table_name='ab_test_events')
    op.drop_table('ab_test_events')
    op.drop_index(op.f('ix_customer_journey_stages_contact_id'), table_name='customer_journey_stages')
    op.drop_table('customer_journey_stages')
    op.drop_index(op.f('ix_crm_deals_owner_id'), table_name='crm_deals')
    op.drop_index(op.f('ix_crm_deals_contact_id'), table_name='crm_deals')
    op.drop_table('crm_deals')
    op.drop_index(op.f('ix_crm_campaign_recipients_tracking_token'), table_name='crm_campaign_recipients')
    op.drop_index(op.f('ix_crm_campaign_recipients_campaign_id'), table_name='crm_campaign_recipients')
    op.drop_table('crm_campaign_recipients')
    op.drop_index(op.f('ix_app_store_plugin_installs_user_id'), table_name='app_store_plugin_installs')
    op.drop_index(op.f('ix_app_store_plugin_installs_plugin_id'), table_name='app_store_plugin_installs')
    op.drop_index(op.f('ix_app_store_plugin_installs_id'), table_name='app_store_plugin_installs')
    op.drop_table('app_store_plugin_installs')
    op.drop_index(op.f('ix_ab_test_variants_experiment_id'), table_name='ab_test_variants')
    op.drop_table('ab_test_variants')
    op.drop_index(op.f('ix_ab_test_decision_logs_experiment_id'), table_name='ab_test_decision_logs')
    op.drop_index(op.f('ix_ab_test_decision_logs_created_at'), table_name='ab_test_decision_logs')
    op.drop_table('ab_test_decision_logs')
    op.drop_table('visitor_logs')
    op.drop_table('team_members')
    op.drop_table('team_invites')
    op.drop_table('platform_opportunities')
    op.drop_table('platform_members')
    op.drop_index(op.f('ix_pages_tenant_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_crm_workflow_logs_owner_id'), table_name='crm_workflow_logs')
    op.drop_table('crm_workflow_logs')
    op.drop_index(op.f('ix_crm_contacts_user_id'), table_name='crm_contacts')
    op.drop_index(op.f('ix_crm_contacts_owner_id'), table_name='crm_contacts')
    op.drop_table('crm_contacts')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_app_store_plugin_versions_plugin_id'), table_name='app_store_plugin_versions')
    op.drop_index(op.f('ix_app_store_plugin_versions_id'), table_name='app_store_plugin_versions')
    op.drop_table('app_store_plugin_versions')
    op.drop_index(op.f('ix_app_store_plugin_reviews_plugin_id'), table_name='app_store_plugin_reviews')
    op.drop_index(op.f('ix_app_store_plugin_reviews_id'), table_name='app_store_plugin_reviews')
    op.drop_table('app_store_plugin_reviews')
    op.drop_index(op.f('ix_api_key_usage_api_key_id'), table_name='api_key_usage')
    op.drop_table('api_key_usage')
    op.drop_index(op.f('ix_ab_tests_user_id'), table_name='ab_tests')
    op.drop_index(op.f('ix_ab_tests_target_brochure_id'), table_name='ab_tests')
    op.drop_index(op.f('ix_ab_tests_status'), table_name='ab_tests')
    op.drop_table('ab_tests')
    op.drop_table('user_tags')
    op.drop_table('trust_network')
    op.drop_table('teams')
    op.drop_index(op.f('ix_reward_redemptions_id'), table_name='reward_redemptions')
    op.drop_index(op.f('ix_reward_redemptions_developer_id'), table_name='reward_redemptions')
    op.drop_table('reward_redemptions')
    op.drop_table('resource_platforms')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_receiver_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_is_read'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('match_records')
    op.drop_index(op.f('ix_developer_rewards_id'), table_name='developer_rewards')
    op.drop_index(op.f('ix_developer_rewards_developer_id'), table_name='developer_rewards')
    op.drop_table('developer_rewards')
    op.drop_index(op.f('ix_developer_reward_balances_id'), table_name='developer_reward_balances')
    op.drop_index(op.f('ix_developer_reward_balances_developer_id'), table_name='developer_reward_balances')
    op.drop_table('developer_reward_balances')
    op.drop_index(op.f('ix_crm_workflow_rules_owner_id'), table_name='crm_workflow_rules')
    op.drop_table('crm_workflow_rules')
    op.drop_index(op.f('ix_crm_pipeline_stages_user_id'), table_name='crm_pipeline_stages')
    op.drop_table('crm_pipeline_stages')
    op.drop_index(op.f('ix_crm_campaigns_owner_id'), table_name='crm_campaigns')
    op.drop_table('crm_campaigns')
    op.drop_index(op.f('ix_brochures_tenant_id'), table_name='brochures')
    op.drop_table('brochures')
    op.drop_index(op.f('ix_app_store_plugins_status'), table_name='app_store_plugins')
    op.drop_index(op.f('ix_app_store_plugins_id'), table_name='app_store_plugins')
    op.drop_index(op.f('ix_app_store_plugins_developer_id'), table_name='app_store_plugins')
    op.drop_index(op.f('ix_app_store_plugins_category'), table_name='app_store_plugins')
    op.drop_table('app_store_plugins')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('rbac_user_roles')
    op.drop_table('rbac_role_permissions')
    op.drop_index(op.f('ix_webhook_subscriptions_user_id'), table_name='webhook_subscriptions')
    op.drop_table('webhook_subscriptions')
    op.drop_index(op.f('ix_usage_counters_user_id'), table_name='usage_counters')
    op.drop_table('usage_counters')
    op.drop_table('unlock_records')
    op.drop_table('trial_records')
    op.drop_table('tenants')
    op.drop_table('social_connections')
    op.drop_table('rbac_roles')
    op.drop_table('payment_orders')
    op.drop_index(op.f('ix_knowledge_models_model_id'), table_name='knowledge_models')
    op.drop_index(op.f('ix_knowledge_models_category'), table_name='knowledge_models')
    op.drop_index('idx_km_model_id', table_name='knowledge_models')
    op.drop_index('idx_km_category', table_name='knowledge_models')
    op.drop_index('idx_km_active', table_name='knowledge_models')
    op.drop_table('knowledge_models')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_integrations_user_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_gaia_training_runs_status'), table_name='gaia_training_runs')
    op.drop_index('idx_gaia_training_status', table_name='gaia_training_runs')
    op.drop_table('gaia_training_runs')
    op.drop_index(op.f('ix_gaia_model_weights_module'), table_name='gaia_model_weights')
    op.drop_index('idx_gaia_weights_module_active', table_name='gaia_model_weights')
    op.drop_table('gaia_model_weights')
    op.drop_index(op.f('ix_gaia_knowledge_source'), table_name='gaia_knowledge')
    op.drop_index(op.f('ix_gaia_knowledge_knowledge_type'), table_name='gaia_knowledge')
    op.drop_index('idx_gaia_knowledge_type', table_name='gaia_knowledge')
    op.drop_index('idx_gaia_knowledge_source', table_name='gaia_knowledge')
    op.drop_index('idx_gaia_knowledge_active', table_name='gaia_knowledge')
    op.drop_table('gaia_knowledge')
    op.drop_index(op.f('ix_gaia_evolution_events_event_type'), table_name='gaia_evolution_events')
    op.drop_index(op.f('ix_gaia_evolution_events_created_at'), table_name='gaia_evolution_events')
    op.drop_index('idx_gaia_event_type_time', table_name='gaia_evolution_events')
    op.drop_index('idx_gaia_event_ref', table_name='gaia_evolution_events')
    op.drop_table('gaia_evolution_events')
    op.drop_table('enterprise_subscriptions')
    op.drop_table('email_campaigns')
    op.drop_index(op.f('ix_developer_apps_user_id'), table_name='developer_apps')
    op.drop_index(op.f('ix_developer_apps_id'), table_name='developer_apps')
    op.drop_index(op.f('ix_developer_apps_client_id'), table_name='developer_apps')
    op.drop_table('developer_apps')
    op.drop_index(op.f('ix_crm_sync_states_provider'), table_name='crm_sync_states')
    op.drop_table('crm_sync_states')
    op.drop_index(op.f('ix_crm_sync_conflicts_sync_state_id'), table_name='crm_sync_conflicts')
    op.drop_index(op.f('ix_crm_sync_conflicts_provider'), table_name='crm_sync_conflicts')
    op.drop_table('crm_sync_conflicts')
    op.drop_index(op.f('ix_crm_documents_owner_id'), table_name='crm_documents')
    op.drop_table('crm_documents')
    op.drop_index('idx_audit_user_id', table_name='audit_logs')
    op.drop_index('idx_audit_user_action', table_name='audit_logs')
    op.drop_index('idx_audit_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
