#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
PG 一键修复 + 迁移 — 正确路径版
管理员身份运行
"""
import os, sys, subprocess, asyncio, time

PGDATA = r"D:\DataBase\PostgreSQL\18\data"
PGHBA = os.path.join(PGDATA, "pg_hba.conf")
PYTHON = sys.executable
BE = r"D:\AI数智名片\backend"

os.system("chcp 65001 >nul")
print("=" * 50)
print("  PG 一键修复 + 迁移")
print("  PG数据目录: " + PGDATA)
print("=" * 50)

# ========== 1. 停PG ==========
print("\n[1/5] 停止 PostgreSQL 服务...")
subprocess.run(r'net stop postgresql-x64-18', shell=True, timeout=15)
time.sleep(2)
print("  OK")

# ========== 2. 写信任认证 ==========
print("\n[2/5] 写入信任认证配置...")
try:
    content = (
        "# Auto-generated by pg_migrate.py\n"
        "local   all   all   trust\n"
        "host    all   all   127.0.0.1/32  trust\n"
        "host    all   all   ::1/128  trust\n"
        "local   replication   all   trust\n"
        "host    replication   all   127.0.0.1/32  trust\n"
        "host    replication   all   ::1/128  trust\n"
    )
    with open(PGHBA, "w", encoding="utf-8") as f:
        f.write(content)
    print("  ✅ pg_hba.conf 已重写")
except Exception as e:
    print(f"  ❌ 错误: {e}")
    input("按回车退出...")
    sys.exit(1)

# ========== 3. 启动PG ==========
print("\n[3/5] 启动 PostgreSQL 服务...")
r = subprocess.run(r'net start postgresql-x64-18', shell=True, capture_output=True, text=True, timeout=15)
out = (r.stdout + r.stderr)
if "started" in out.lower() or "已启动" in out or "already" in out.lower():
    print("  ✅ PG 已启动")
else:
    print(f"  输出: {out[:200]}")
time.sleep(3)

# ========== 4. 创建数据库 + 迁移 ==========
print("\n[4/5] 创建数据库 + Alembic 迁移...")

async def create_db():
    import asyncpg
    conn = await asyncpg.connect(user='postgres', host='127.0.0.1', port=5432)
    try:
        await conn.execute("CREATE DATABASE digital_brochure")
        print("  ✅ 数据库 digital_brochure 创建成功")
    except Exception as e:
        if "already exists" in str(e):
            print("  ✅ 数据库 digital_brochure 已存在")
        else:
            print(f"  ⚠️ {e}")
    await conn.close()

try:
    asyncio.run(create_db())
except Exception as e:
    print(f"  ⚠️ 数据库操作: {e}")

# Alembic 迁移
os.chdir(BE)
code = "import sys; sys.path.insert(0,'.'); from alembic.config import Config; from alembic import command; command.upgrade(Config('alembic.ini'),'head'); print('OK')"
r = subprocess.run([PYTHON, "-c", code], capture_output=True, text=True, timeout=30)
if "OK" in r.stdout:
    print("  ✅ Alembic 迁移完成")
else:
    print(f"  ⚠️ 迁移输出: {(r.stdout+r.stderr)[:300]}")

# ========== 5. 验证 ==========
print("\n[5/5] 验证迁移结果...")

async def verify():
    import asyncpg
    conn = await asyncpg.connect(user='postgres', host='127.0.0.1', port=5432, database='digital_brochure')
    tables = await conn.fetch("SELECT table_name FROM information_schema.tables WHERE table_schema='public' ORDER BY table_name")
    print(f"  📊 digital_brochure 共 {len(tables)} 个表:")
    for t in tables:
        print(f"     📄 {t['table_name']}")
    await conn.close()

try:
    asyncio.run(verify())
except Exception as e:
    print(f"  ⚠️ 验证: {e}")

print("\n" + "=" * 50)
print("  ✅ 全部完成！")
print("=" * 50)
print("\n下一步:")
print("  1. taskkill /f /im python.exe    # 关旧后端")
print("  2. 双击 D:\\AI数智名片\\start_backend.bat")
input("\n按回车退出...")
